### PR TITLE
[FEAT] Implement io redirection

### PR DESCRIPTION
**Pull request by LeaYeh**
yes | (head -1 && (head -2 | (head -3 && head -4))) | cat | wc -l
yes | (echo 1 && (echo 2 | (echo 3 && echo 4))) | cat
yes | (echo 1 && (echo 2 | (echo 3 && echo 4))) | cat | wc -l
yes | (head -1 && (head -2 | (head -3 && head -4))) | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | cat | wc -l

cat < Makefile << eof > out1(000) >> out2

Th behavio of heredoc with Ctrl-D is incorrect, not sure it's related to signal handle or not

### CODE REVIEW

**Comment by itislu** [comment]
```sh
< Makefile > out
```
The file `out` should get created, but it doesn't.

**Comment by LeaYeh** [comment]
Resolved #116

**Comment by LeaYeh** [comment]
Resolved #109

**Review by itislu — APPROVED** [review]
Merging without testing everything because it blocks our development progress.
Definitely still need to do more testing of io redirection once merged.

**Pull request merged**
