### PR TITLE
[FIX] Fix multi `-n` detection for echo

### PR DESCRIPTION
**Pull request by itislu**
* Resolves issue #158

### CODE REVIEW

**Review by LeaYeh — COMMENTED** [review]
Why not just strcmp and check len==2?

**Comment by itislu** [comment]
Because it also has to work with `-nnnnn`. For any of them, so `-nnnn -n -nnnnn -nnnn` is also valid.
I hope I don't understand you incorrectly.

**Comment by LeaYeh** [comment]
So weird -nnnn should work, for me it sounds like bug 🧐

**Review by LeaYeh — APPROVED** [review]

**Comment by itislu** [comment]
I agree, it's very weird...
But the tester also tests for it, so it helps the score :)

**Pull request merged**
